import json, os
FPS = 24
TOTAL = 600
T_HOLA, T_NAME, T_TRAIT, T_ASK, T_BYE = (6, 46, 152, 320, 482)
T_PRAISE = 428
TIMES = (T_HOLA, T_NAME, T_TRAIT, T_ASK, T_PRAISE, T_BYE)
VOICES = {'pimo': {'pitch': 1.45, 'tempo': 1.12}, 'ruki': {'pitch': 1.15, 'tempo': 1.0}, 'luma': {'pitch': 1.62, 'tempo': 1.15}, 'tuki': {'pitch': 1.5, 'tempo': 1.18}, 'moki': {'pitch': 1.42, 'tempo': 1.0}, 'bopi': {'pitch': 1.3, 'tempo': 1.15, 'robot': True}, 'bolita': {'pitch': 1.58, 'tempo': 1.2}, 'gruno': {'pitch': 0.92, 'tempo': 1.0}}
CHARS = {'pimo': {'name': 'PIMO', 'trait': '¡CURIOSO!', 'gesture': 'wave', 'emote': '?', 'lines': ['¡Hola, hola!', '¡Soy Pimo, y soy muy curioso!', 'Me encanta preguntar: ¿por qué? ¿Y por qué? ¡Preguntando se aprende!', '¿Tú también eres curioso? ¡Dime algo que quieras saber!', '¡Muy bien! ¡Qué buena pregunta!', '¡Nos vemos pronto, curioso!']}, 'ruki': {'name': 'RUKI', 'trait': '¡TRANQUILO!', 'gesture': 'breathe', 'emote': 'bubble', 'lines': ['Hola, amigo...', 'Soy Ruki. Yo soy muy tranquilo.', 'Cuando me enfado, respiro hondo... ¡y me calmo!', '¿Lo hacemos juntos? Coge aire... y suéltalo despacito.', '¡Genial! ¿A que te sientes mejor?', 'Hasta pronto. Respira y sonríe.']}, 'luma': {'name': 'LUMA', 'trait': '¡ALEGRE!', 'gesture': 'wave', 'emote': 'spark', 'lines': ['¡Hola, hola!', '¡Soy Luma, y soy muy alegre!', '¡Cuando sonrío, brillo muchísimo! Y si estoy triste... lo cuento.', '¿Me enseñas tu sonrisa? Una, dos y... ¡tres!', '¡Oooh, qué sonrisa más bonita!', '¡Hasta pronto! ¡Sigue brillando!']}, 'tuki': {'name': 'TUKI', 'trait': '¡JUGUETÓN!', 'gesture': 'spin', 'emote': '!', 'lines': ['¡Eh, eh, hola!', '¡Soy Tuki, y soy súper juguetón!', '¡Me encanta saltar, girar y bailar! ¡Moverse es divertidísimo!', '¿Saltas conmigo? ¡Uno, dos y tres!', '¡Bieeen! ¡Saltas genial!', '¡Hasta luego! ¡A moverse!']}, 'moki': {'name': 'MOKI', 'trait': '¡SOÑADOR!', 'gesture': 'sway', 'emote': 'Z', 'lines': ['Hola...', 'Soy Moki, una nube soñadora.', 'Me encanta imaginar cosas... ¡un dragón de algodón! ¡Un barco de nubes!', 'Cierra los ojos... ¿qué te imaginas tú?', 'Mmm... ¡qué sueño tan bonito!', 'Dulces sueños, amigo...']}, 'bopi': {'name': 'BOPI', 'trait': '¡ORDENADO!', 'gesture': 'hops', 'emote': '123', 'lines': ['Hola. ¡Bip, bop!', 'Soy Bopi, un robot muy ordenado.', 'Cada cosa en su sitio: ¡los juguetes en la caja!', '¿Me ayudas a contar? Uno, dos, tres...', '¡Correcto! ¡Eres un gran ayudante!', 'Bopi se despide. ¡Bip, bop!']}, 'bolita': {'name': 'BOLITA', 'trait': '¡VALIENTE!', 'gesture': 'bounce', 'emote': '!', 'lines': ['¡Hola, hola, hola!', '¡Soy Bolita, y soy muy valiente!', '¡Siempre digo: yo primero! Pero... juntos es mucho mejor.', '¿Jugamos juntos? ¡Choca esos cinco!', '¡Bien! ¡Juntos somos un equipo!', '¡Hasta la próxima, equipo!']}, 'gruno': {'name': 'DOCTOR GRUÑO', 'trait': '¡INVENTOR!', 'gesture': 'bounce', 'emote': 'poof', 'lines': ['Vaya, vaya, vaya...', '¡Soy el Doctor Gruño, el gran inventor!', '¡Mis inventos son geniales! Bueno... casi siempre.', 'Mirad mi nueva máquina... ¡Ay! ¡Ups!', 'Bah... ¡de los errores también se aprende!', '¡Ya veréis, Pimoruki! ¡Ya veréis!']}}
ORDER = ['pimo', 'ruki', 'luma', 'tuki', 'moki', 'bopi', 'bolita', 'gruno']

def current():
    cid = os.environ.get('CHAR')
    p = os.environ.get('SPEC_FILE')
    if not cid and p and os.path.exists(p):
        cid = json.load(open(p)).get('char')
    return cid or 'pimo'
