REGISTRY = {
    "flower_pot": {"styles": 3, "envs": ["plaza", "patio", "casa"], "tags": ["planta"]},
    "bush": {"styles": 3, "envs": ["plaza", "patio", "otono", "halloween"], "tags": ["planta"]},
    "toy_blocks": {"styles": 3, "envs": ["plaza", "casa", "lab"], "tags": ["juguete"]},
    "mushroom_stool": {"styles": 3, "envs": ["plaza", "patio", "otono", "halloween"], "tags": ["asiento"]},
    "fence": {"styles": 3, "envs": ["patio", "plaza", "halloween"], "tags": ["borde"]},
    "lamp_post": {"styles": 3, "envs": ["plaza", "otono"], "tags": ["luz"]},
    "bench": {"styles": 3, "envs": ["plaza", "patio"], "tags": ["asiento"]},
    "pebbles": {"styles": 3, "envs": ["any"], "tags": ["suelo"]},
    "bunting": {"styles": 3, "envs": ["plaza", "casa", "lab"], "tags": ["fiesta"]},
    "gear_tower": {"styles": 3, "envs": ["lab"], "tags": ["invento"]},
    "leaf_pile": {"styles": 3, "envs": ["otono", "halloween"], "tags": ["otoño"]},
    "ball_basket": {"styles": 3, "envs": ["patio", "casa"], "tags": ["juguete"]},
    "soft_token": {"styles": 3, "envs": ["patio", "casa", "aula"], "tags": ["juguete", "contar"]},
    "play_mat": {"styles": 3, "envs": ["patio", "casa", "aula"], "tags": ["suelo", "juego"]},
    "floor_lamp": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["luz", "sombra"]},
    "desk_bell": {"styles": 3, "envs": ["casa", "aula", "lab", "plaza"], "tags": ["sonido", "musica"], "decor": False},
    "toy_drum": {"styles": 3, "envs": ["casa", "aula", "lab", "plaza", "patio"], "tags": ["sonido", "musica"], "decor": False},
    "colander": {"styles": 3, "envs": ["cocina", "casa", "patio"], "tags": ["cocina", "agua"], "decor": False},
    "clear_cup": {"styles": 3, "envs": ["cocina", "casa", "patio", "lab"], "tags": ["cocina", "agua"], "decor": False},
    "birdhouse": {"styles": 3, "envs": ["patio", "plaza", "otono"], "tags": ["jardin"]},
    "planter_box": {"styles": 3, "envs": ["patio", "plaza", "casa"], "tags": ["planta"]},
    "pouf": {"styles": 3, "envs": ["casa", "aula"], "tags": ["asiento"]},
    "finish_line": {"styles": 3, "envs": ["plaza", "patio"], "tags": ["juego", "carrera"], "decor": False},
    "paint_palette": {"styles": 3, "envs": ["casa", "aula", "patio"], "tags": ["arte", "colores"], "decor": False},
    "lidded_box": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["caja", "misterio"], "decor": False},
    "toy_speaker": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["sonido"], "decor": False},
    "star_plush": {"styles": 3, "envs": ["casa", "aula"], "tags": ["juguete", "cuento"], "decor": False},
    "play_door": {"styles": 3, "envs": ["casa", "aula", "patio"], "tags": ["puerta"], "decor": False},
    "snack_plate": {"styles": 3, "envs": ["casa", "cocina", "patio"], "tags": ["cocina", "merienda"], "decor": False},
    "bubble_blower": {"styles": 3, "envs": ["lab", "patio"], "tags": ["invento", "burbujas"], "decor": False},
    "play_ball": {"styles": 3, "envs": ["patio", "casa", "plaza", "aula"], "tags": ["juguete"], "decor": False},
    "number_stand": {"styles": 3, "envs": ["plaza", "patio", "casa", "aula"], "tags": ["numeros", "contar"], "decor": False},
    "toy_magnet": {"styles": 3, "envs": ["lab", "casa", "aula"], "tags": ["ciencia", "iman"], "decor": False},
    "fruit": {"styles": 3, "envs": ["cocina", "casa", "patio", "lab"], "tags": ["comida"], "decor": False},
    "low_table": {"styles": 3, "envs": ["casa", "lab", "aula", "cocina", "patio"], "tags": ["mueble"], "decor": False},
    "play_step": {"styles": 3, "envs": ["patio", "casa", "aula", "plaza"], "tags": ["plataforma", "juego"], "decor": False},
    "sponge": {"styles": 3, "envs": ["cocina", "casa", "lab"], "tags": ["limpieza", "agua"], "decor": False},
    "big_spoon": {"styles": 3, "envs": ["cocina", "casa", "lab"], "tags": ["cocina"], "decor": False},
    "mixing_bowl": {"styles": 3, "envs": ["cocina", "casa", "lab"], "tags": ["cocina", "agua"], "decor": False},
    "toy_elephant": {"styles": 3, "envs": ["plaza", "casa", "patio", "aula"], "tags": ["juguete", "animal"], "decor": False},
    "net_swing": {"styles": 3, "envs": ["plaza", "patio", "casa"], "tags": ["juguete", "columpio"], "decor": False},
    "bridge_kit": {"styles": 3, "envs": ["patio", "casa", "aula"], "tags": ["construir", "juguete"], "decor": False},
    "toy_torch": {"styles": 3, "envs": ["lab", "casa", "aula", "patio"], "tags": ["luz", "buscar"], "decor": False},
    "explain_panel": {"styles": 3, "envs": ["lab", "aula", "casa", "patio", "plaza"], "tags": ["ilustracion", "ciencia"], "decor": False},
    "tiny_shoes": {"styles": 3, "envs": ["casa", "aula", "patio"], "tags": ["juguete", "ropa"], "decor": False},
    "time_clock": {"styles": 3, "envs": ["casa", "aula", "lab", "cocina"], "tags": ["tiempo", "reloj"], "decor": False},
    "water_tray": {"styles": 3, "envs": ["patio", "lab", "casa", "cocina", "aula"], "tags": ["agua", "ciencia"], "decor": False},
    "ring_fence": {"styles": 3, "envs": ["patio", "plaza", "casa"], "tags": ["juguete", "borde"], "decor": False},
    "float_item": {"styles": 3, "envs": ["patio", "lab", "casa", "aula"], "tags": ["agua", "ciencia", "materiales"], "decor": False},
    "boat_sticker": {"styles": 3, "envs": ["patio", "casa", "aula", "lab"], "tags": ["juguete", "barco"], "decor": False},
    "gourd_trio": {"styles": 3, "envs": ["halloween", "otono", "plaza"], "tags": ["otoño", "calabaza"]},
    "led_lantern": {"styles": 3, "envs": ["halloween", "otono", "plaza", "casa"], "tags": ["luz", "noche"]},
    "hay_seat": {"styles": 3, "envs": ["halloween", "otono", "patio"], "tags": ["asiento", "otoño"]},
    "leaf_pad": {"styles": 3, "envs": ["halloween", "otono", "patio", "plaza"], "tags": ["hoja", "plataforma"], "decor": False},
    "date_card": {"styles": 3, "envs": ["halloween", "casa", "aula", "otono"], "tags": ["calendario", "fecha"], "decor": False},
    "hand_fan": {"styles": 3, "envs": ["casa", "patio", "aula", "plaza"], "tags": ["aire", "viento"], "decor": False},
    "pinwheel": {"styles": 3, "envs": ["patio", "plaza", "casa", "aula"], "tags": ["aire", "viento", "juguete"], "decor": False},
}
