REGISTRY = {
    "flower_pot": {"styles": 3, "envs": ["plaza", "patio", "casa"], "tags": ["planta"]},
    "bush": {"styles": 3, "envs": ["plaza", "patio", "otono"], "tags": ["planta"]},
    "toy_blocks": {"styles": 3, "envs": ["plaza", "casa", "lab"], "tags": ["juguete"]},
    "mushroom_stool": {"styles": 3, "envs": ["plaza", "patio", "otono"], "tags": ["asiento"]},
    "fence": {"styles": 3, "envs": ["patio", "plaza"], "tags": ["borde"]},
    "lamp_post": {"styles": 3, "envs": ["plaza", "otono"], "tags": ["luz"]},
    "bench": {"styles": 3, "envs": ["plaza", "patio"], "tags": ["asiento"]},
    "pebbles": {"styles": 3, "envs": ["any"], "tags": ["suelo"]},
    "bunting": {"styles": 3, "envs": ["plaza", "casa", "lab"], "tags": ["fiesta"]},
    "gear_tower": {"styles": 3, "envs": ["lab"], "tags": ["invento"]},
    "leaf_pile": {"styles": 3, "envs": ["otono"], "tags": ["otoño"]},
    "ball_basket": {"styles": 3, "envs": ["patio", "casa"], "tags": ["juguete"]},
    "soft_token": {"styles": 3, "envs": ["patio", "casa", "aula"], "tags": ["juguete", "contar"]},
    "play_mat": {"styles": 3, "envs": ["patio", "casa", "aula"], "tags": ["suelo", "juego"]},
    "floor_lamp": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["luz", "sombra"]},
    "desk_bell": {"styles": 3, "envs": ["casa", "aula", "lab", "plaza"], "tags": ["sonido", "musica"], "decor": False},
    "toy_drum": {"styles": 3, "envs": ["casa", "aula", "lab", "plaza", "patio"], "tags": ["sonido", "musica"], "decor": False},
    "colander": {"styles": 3, "envs": ["cocina", "casa", "patio"], "tags": ["cocina", "agua"], "decor": False},
    "clear_cup": {"styles": 3, "envs": ["cocina", "casa", "patio", "lab"], "tags": ["cocina", "agua"], "decor": False},
    "birdhouse": {"styles": 3, "envs": ["patio", "plaza", "otono"], "tags": ["jardin"]},
    "planter_box": {"styles": 3, "envs": ["patio", "plaza", "casa"], "tags": ["planta"]},
    "pouf": {"styles": 3, "envs": ["casa", "aula"], "tags": ["asiento"]},
    "finish_line": {"styles": 3, "envs": ["plaza", "patio"], "tags": ["juego", "carrera"], "decor": False},
    "paint_palette": {"styles": 3, "envs": ["casa", "aula", "patio"], "tags": ["arte", "colores"], "decor": False},
    "lidded_box": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["caja", "misterio"], "decor": False},
    "toy_speaker": {"styles": 3, "envs": ["casa", "aula", "lab"], "tags": ["sonido"], "decor": False},
    "star_plush": {"styles": 3, "envs": ["casa", "aula"], "tags": ["juguete", "cuento"], "decor": False},
    "play_door": {"styles": 3, "envs": ["casa", "aula", "patio"], "tags": ["puerta"], "decor": False},
}
